/**
 * Comprehensive API Client for Portfolio Admin Panel
 * 
 * This file contains all API definitions, interfaces, and methods 
 * to interact with the backend server.
 * 
 * Generated by Trae AI
 */

import axios, { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';
import { useAdminAuthStore } from '../store/adminAuthStore';

// ==========================================
// CONFIGURATION
// ==========================================

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:3000/api';

const apiClient: AxiosInstance = axios.create({
  baseURL: API_URL,
  headers: {
    'Content-Type': 'application/json',
  },
  timeout: 60000, // 60 seconds timeout for AI generation
});

// Request Interceptor
apiClient.interceptors.request.use(
  (config) => {
    const token = useAdminAuthStore.getState().token;
    if (token) {
      config.headers.Authorization = `Bearer ${token}`;
    }
    // Add public API key if needed for public endpoints (though admin mostly uses Bearer)
    // config.headers['x-api-key'] = import.meta.env.VITE_PUBLIC_API_KEY; 
    return config;
  },
  (error) => Promise.reject(error)
);

// Response Interceptor
apiClient.interceptors.response.use(
  (response) => response,
  async (error) => {
    const originalRequest = error.config;
    
    // Handle 401 Unauthorized (Token Expired) or 403 Forbidden (Invalid Token)
    if ((error.response?.status === 401 || error.response?.status === 403) && !originalRequest._retry) {
      originalRequest._retry = true;
      
      // Logout user if token is invalid
      useAdminAuthStore.getState().logout();
      window.location.href = '/admin/login';
      
      return Promise.reject(error);
    }
    
    // Handle Network Errors (Connection Refused, etc.) - DO NOT LOGOUT
    if (!error.response) {
        console.error('Network Error:', error.message);
        // We don't logout here, so user stays on the page but sees an error
        return Promise.reject(error);
    }

    // Handle Global Errors
    if (error.response?.status === 500) {
      console.error('Server Error:', error.response.data);
    }
    
    return Promise.reject(error);
  }
);

// ==========================================
// TYPE DEFINITIONS
// ==========================================

// --- Common ---
export interface ApiResponse<T = any> {
  message?: string;
  data?: T;
  [key: string]: any;
}

export interface PaginationParams {
  page?: number;
  limit?: number;
  search?: string;
  sortBy?: string;
  order?: 'asc' | 'desc';
}

// --- Auth ---
export interface User {
  id: string;
  username: string;
  email: string;
  avatar?: string;
}

export interface LoginResponse {
  token: string;
  user: User;
}

// --- Profile ---
export interface Profile {
  id?: number;
  full_name: string;
  headline: string;
  bio: string;
  avatar_url?: string;
  resume_url?: string;
  contact_email: string;
  contact_phone?: string;
  location?: string;
  website?: string;
  status: 'available' | 'busy' | 'offline';
}

export interface SocialLink {
  id: number;
  platform: string;
  url: string;
  icon_name?: string;
  is_active: boolean;
}

// --- Projects ---
export interface ProjectCategory {
  id: number;
  name: string;
  slug: string;
  _count?: {
    projects: number;
  };
}

export interface Project {
  id: number;
  title: string;
  slug: string;
  description: string;
  content?: string;
  tech: string | string[]; // Backend field
  demo_urls?: string | any[];
  repo_urls?: string | any[];
  video_urls?: string | any[];
  cover_image?: string;
  cover_image_url?: string;
  images?: any[]; // ProjectImage[]
  categoryId?: number;
  category?: ProjectCategory;
  is_published: boolean;
  publish_at?: string;
  order: number;
  seo_title?: string;
  seo_description?: string;
  seo_keywords?: string | string[];
  createdAt?: string;
  updatedAt?: string;
}

export interface CreateProjectDTO extends Omit<Project, 'id' | 'createdAt' | 'updatedAt' | 'category' | 'images'> {
  image_urls?: string[];
  summaries?: any[];
}
export interface UpdateProjectDTO extends Partial<CreateProjectDTO> {}

// --- Skills ---
export interface SkillCategory {
  id: number;
  name: string;
  description?: string;
  sort_order: number;
}

export interface Skill {
  id: number;
  name: string;
  category_id?: number;
  proficiency: number; // 0-100
  icon_url?: string;
  is_featured: boolean;
  sort_order: number;
  category?: SkillCategory; // Joined
}

// --- Education ---
export interface Education {
  id: number;
  institution: string;
  degree: string;
  field_of_study?: string;
  start_date: string; // ISO Date or Year
  end_date?: string; // ISO Date or Year or "Present"
  grade?: string;
  description?: string;
  logo_url?: string;
  sort_order: number;
}

// --- Experience ---
export interface Experience {
  id: number;
  company: string;
  position: string;
  location?: string;
  start_date: string;
  end_date?: string;
  is_current: boolean;
  description: string; // Rich text
  logo_url?: string;
  technologies?: string[];
  sort_order: number;
}

// --- Certificates ---
export interface CertificateCategory {
  id: number;
  name: string;
  sort_order: number;
}

export interface Certificate {
  id: number;
  name: string;
  issuer: string;
  issue_date: string;
  expiration_date?: string;
  credential_id?: string;
  credential_url?: string;
  image_url?: string;
  category_id?: number;
  category?: CertificateCategory;
}

// --- Blog ---
export interface BlogCategory {
  id: number;
  name: string;
  slug: string;
}

export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  excerpt?: string;
  content: string;
  cover_image_url?: string;
  author_id?: number;
  category_id?: number;
  tags?: string[];
  is_published: boolean;
  published_at?: string;
  views: number;
  category?: BlogCategory;
}

// --- Communication ---
export interface Message {
  id: number;
  name: string;
  email: string;
  subject?: string;
  message: string;
  is_read: boolean;
  created_at: string;
}

export interface Subscriber {
  id: number;
  email: string;
  is_active: boolean;
  subscribed_at: string;
}

export interface WATemplate {
  id: number;
  name: string;
  message: string;
  category: string;
  is_active: boolean;
}

// --- Upload ---
export interface UploadResponse {
  url: string;
  fileName: string;
  mimeType: string;
  size: number;
}

// ==========================================
// API METHODS
// ==========================================

export const api = {
  // ----------------------------------------
  // Auth
  // ----------------------------------------
  auth: {
    login: async (credentials: { email: string; password: string }): Promise<LoginResponse> => {
      const response = await apiClient.post<LoginResponse>('/auth/login', credentials);
      return response.data;
    },
    register: async (data: any): Promise<User> => {
      const response = await apiClient.post<User>('/auth/register', data);
      return response.data;
    },
    getMe: async (): Promise<User> => {
      const response = await apiClient.get<User>('/auth/me');
      return response.data;
    },
    updateMe: async (data: Partial<User> & { password?: string }): Promise<User> => {
      const response = await apiClient.put<User>('/auth/me', data);
      return response.data;
    },
  },

  // ----------------------------------------
  // Content (Home, About, Settings)
  // ----------------------------------------
  content: {
    home: {
      get: async (): Promise<any> => {
        const response = await apiClient.get('/home-content');
        return response.data;
      },
      update: async (data: any): Promise<any> => {
        const response = await apiClient.post('/home-content', data);
        return response.data;
      },
    },
    about: {
      get: async (): Promise<any> => {
        const response = await apiClient.get('/about-content');
        return response.data;
      },
      update: async (data: any): Promise<any> => {
        const response = await apiClient.post('/about-content', data);
        return response.data;
      },
    },
    settings: {
      get: async (): Promise<any> => {
        const response = await apiClient.get('/settings');
        return response.data;
      },
      update: async (data: any): Promise<any> => {
        const response = await apiClient.post('/settings', data);
        return response.data;
      },
    },
  },

  // ----------------------------------------
  // Profile
  // ----------------------------------------
  profile: {
    get: async (): Promise<Profile> => {
      const response = await apiClient.get<Profile>('/profile');
      return response.data;
    },
    update: async (data: Partial<Profile>): Promise<Profile> => {
      // The backend endpoint might be /profile (POST) or /profile/:id (PUT)
      // Based on route analysis: router.post('/profile', ...)
      const response = await apiClient.post<Profile>('/profile', data);
      return response.data;
    },
  },

  socialLinks: {
    getAll: async (): Promise<SocialLink[]> => {
      const response = await apiClient.get<SocialLink[]>('/social-links');
      return response.data;
    },
    create: async (data: Omit<SocialLink, 'id'>): Promise<SocialLink> => {
      const response = await apiClient.post<SocialLink>('/social-links', data);
      return response.data;
    },
    update: async (id: number, data: Partial<SocialLink>): Promise<SocialLink> => {
      const response = await apiClient.put<SocialLink>(`/social-links/${id}`, data);
      return response.data;
    },
    delete: async (id: number): Promise<void> => {
      await apiClient.delete(`/social-links/${id}`);
    },
  },

  // ----------------------------------------
  // Dashboard
  // ----------------------------------------
  dashboard: {
    getStats: async (): Promise<any> => {
      const response = await apiClient.get('/admin/dashboard-stats');
      return response.data;
    },
  },

  // ----------------------------------------
  // Projects
  // ----------------------------------------
  projects: {
    getAll: async (params?: PaginationParams): Promise<Project[]> => {
      const response = await apiClient.get<Project[]>('/projects', { params });
      return response.data;
    },
    getOne: async (idOrSlug: string | number): Promise<Project> => {
      // Determine if ID or Slug (backend logic might vary, usually slug is for public, ID for admin)
      // But project.routes.ts has /:slug for public and /:id (PUT/DELETE) for admin.
      // Admin might need to fetch by ID. Let's assume getProjectBySlug works for both or we rely on the list.
      // Wait, standard CRUD usually needs GET /projects/:id. 
      // The route file says: router.get('/:slug', publicApiGuard, getProjectBySlug);
      // It doesn't seem to have a specific GET /:id for admin explicitly unless getProjectBySlug handles IDs too.
      // If not, we might need to find from the list or fix backend.
      // For now, let's use the slug endpoint or assume list is enough.
      const response = await apiClient.get<Project>(`/projects/${idOrSlug}`);
      return response.data;
    },
    create: async (data: CreateProjectDTO): Promise<Project> => {
      const response = await apiClient.post<Project>('/projects', data);
      return response.data;
    },
    update: async (id: number, data: UpdateProjectDTO): Promise<Project> => {
      const response = await apiClient.put<Project>(`/projects/${id}`, data);
      return response.data;
    },
    delete: async (id: number): Promise<void> => {
      await apiClient.delete(`/projects/${id}`);
    },
  },

  projectCategories: {
    getAll: async (): Promise<ProjectCategory[]> => {
      const response = await apiClient.get<ProjectCategory[]>('/projects/categories');
      return response.data;
    },
    create: async (data: any): Promise<ProjectCategory> => {
      const response = await apiClient.post<ProjectCategory>('/projects/categories', data);
      return response.data;
    },
    update: async (id: number, data: any): Promise<ProjectCategory> => {
      const response = await apiClient.put<ProjectCategory>(`/projects/categories/${id}`, data);
      return response.data;
    },
    delete: async (id: number): Promise<void> => {
      await apiClient.delete(`/projects/categories/${id}`);
    },
  },

  // ----------------------------------------
  // Resume (Skills, Experience, Education)
  // ----------------------------------------
  skills: {
    getAll: async (): Promise<Skill[]> => {
      const response = await apiClient.get<Skill[]>('/skills');
      return response.data;
    },
    create: async (data: any): Promise<Skill> => {
      const response = await apiClient.post<Skill>('/skills', data);
      return response.data;
    },
    update: async (id: number, data: any): Promise<Skill> => {
      const response = await apiClient.put<Skill>(`/skills/${id}`, data);
      return response.data;
    },
    delete: async (id: number): Promise<void> => {
      await apiClient.delete(`/skills/${id}`);
    },
  },

  skillCategories: {
    getAll: async (): Promise<SkillCategory[]> => {
      const response = await apiClient.get<SkillCategory[]>('/skill-categories');
      return response.data;
    },
    create: async (data: any): Promise<SkillCategory> => {
      const response = await apiClient.post<SkillCategory>('/skill-categories', data);
      return response.data;
    },
    update: async (id: number, data: any): Promise<SkillCategory> => {
      const response = await apiClient.put<SkillCategory>(`/skill-categories/${id}`, data);
      return response.data;
    },
    delete: async (id: number): Promise<void> => {
      await apiClient.delete(`/skill-categories/${id}`);
    },
  },

  education: {
    getAll: async (): Promise<Education[]> => {
      const response = await apiClient.get<Education[]>('/education');
      return response.data;
    },
    create: async (data: any): Promise<Education> => {
      const response = await apiClient.post<Education>('/education', data);
      return response.data;
    },
    update: async (id: number, data: any): Promise<Education> => {
      const response = await apiClient.put<Education>(`/education/${id}`, data);
      return response.data;
    },
    delete: async (id: number): Promise<void> => {
      await apiClient.delete(`/education/${id}`);
    },
  },

  // ----------------------------------------
  // Projects
  // ----------------------------------------
  projects: {
    getAll: async (params?: any): Promise<Project[]> => {
      const response = await apiClient.get<any>('/projects', { params });
      if (Array.isArray(response.data)) {
        return response.data;
      } else if (response.data && Array.isArray(response.data.data)) {
        return response.data.data;
      }
      return [];
    },
    getById: async (id: number): Promise<Project> => {
        const response = await apiClient.get<Project>(`/projects/${id}/details`);
        return response.data;
    },
    create: async (data: any): Promise<Project> => {
      const response = await apiClient.post<Project>('/projects', data);
      return response.data;
    },
    update: async (id: number, data: any): Promise<Project> => {
      const response = await apiClient.put<Project>(`/projects/${id}`, data);
      return response.data;
    },
    delete: async (id: number): Promise<void> => {
      await apiClient.delete(`/projects/${id}`);
    },
    
    // Summaries
    createSummary: async (projectId: number, data: { content: string, variant?: string }): Promise<any> => {
        const response = await apiClient.post(`/projects/${projectId}/summaries`, data);
        return response.data;
    },
    deleteSummary: async (summaryId: number): Promise<void> => {
        await apiClient.delete(`/projects/summaries/${summaryId}`);
    }
  },

  // ----------------------------------------
  // Experience
  experience: {
    getAll: async (): Promise<Experience[]> => {
      const response = await apiClient.get<Experience[]>('/experience');
      return response.data;
    },
    create: async (data: any): Promise<Experience> => {
      const response = await apiClient.post<Experience>('/experience', data);
      return response.data;
    },
    update: async (id: number, data: any): Promise<Experience> => {
      const response = await apiClient.put<Experience>(`/experience/${id}`, data);
      return response.data;
    },
    delete: async (id: number): Promise<void> => {
      await apiClient.delete(`/experience/${id}`);
    },
  },

  certificates: {
    getAll: async (): Promise<Certificate[]> => {
      const response = await apiClient.get<Certificate[]>('/certificates');
      return response.data;
    },
    create: async (data: any): Promise<Certificate> => {
      const response = await apiClient.post<Certificate>('/certificates', data);
      return response.data;
    },
    update: async (id: number, data: any): Promise<Certificate> => {
      const response = await apiClient.put<Certificate>(`/certificates/${id}`, data);
      return response.data;
    },
    delete: async (id: number): Promise<void> => {
      await apiClient.delete(`/certificates/${id}`);
    },
  },

  // ----------------------------------------
  // Blog
  // ----------------------------------------
  blog: {
    posts: {
      getAll: async (params?: any): Promise<BlogPost[]> => {
        const response = await apiClient.get<BlogPost[]>('/blog-posts', { params });
        return response.data;
      },
      getBySlug: async (slug: string): Promise<BlogPost> => {
        const response = await apiClient.get<BlogPost>('/blog-posts/by_slug', { params: { slug } });
        return response.data;
      },
      create: async (data: any): Promise<BlogPost> => {
        const response = await apiClient.post<BlogPost>('/blog-posts', data);
        return response.data;
      },
      update: async (id: number, data: any): Promise<BlogPost> => {
        const response = await apiClient.put<BlogPost>(`/blog-posts/${id}`, data);
        return response.data;
      },
      delete: async (id: number): Promise<void> => {
        await apiClient.delete(`/blog-posts/${id}`);
      },
    },
    categories: {
      getAll: async (): Promise<BlogCategory[]> => {
        const response = await apiClient.get<BlogCategory[]>('/blog-categories');
        return response.data;
      },
      create: async (data: any): Promise<BlogCategory> => {
        const response = await apiClient.post<BlogCategory>('/blog-categories', data);
        return response.data;
      },
      update: async (id: number, data: any): Promise<BlogCategory> => {
        const response = await apiClient.put<BlogCategory>(`/blog-categories/${id}`, data);
        return response.data;
      },
      delete: async (id: number): Promise<void> => {
        await apiClient.delete(`/blog-categories/${id}`);
      },
    },
  },

  // ----------------------------------------
  // Communication
  // ----------------------------------------
  messages: {
    getAll: async (): Promise<Message[]> => {
      const response = await apiClient.get<Message[]>('/messages');
      return response.data;
    },
    create: async (data: any): Promise<Message> => {
      const response = await apiClient.post<Message>('/messages', data);
      return response.data;
    },
    markRead: async (id: number): Promise<Message> => {
      const response = await apiClient.put<Message>(`/messages/${id}`, { is_read: true });
      return response.data;
    },
    delete: async (id: number): Promise<void> => {
      await apiClient.delete(`/messages/${id}`);
    },
  },

  waTemplates: {
    getAll: async (): Promise<WATemplate[]> => {
      const response = await apiClient.get<WATemplate[]>('/wa-templates');
      return response.data;
    },
    create: async (data: any): Promise<WATemplate> => {
      const response = await apiClient.post<WATemplate>('/wa-templates', data);
      return response.data;
    },
    update: async (id: number, data: any): Promise<WATemplate> => {
      const response = await apiClient.put<WATemplate>(`/wa-templates/${id}`, data);
      return response.data;
    },
    delete: async (id: number): Promise<void> => {
      await apiClient.delete(`/wa-templates/${id}`);
    },
  },

  // ----------------------------------------
  // Upload
  // ----------------------------------------
  upload: {
    file: async (file: File): Promise<UploadResponse> => {
      const formData = new FormData();
      formData.append('file', file);
      const response = await apiClient.post<UploadResponse>('/upload', formData, {
        headers: { 'Content-Type': 'multipart/form-data' },
      });
      return response.data;
    },
  },

  // ----------------------------------------
  // AI Service
  // ----------------------------------------
  ai: {
    generateContent: (data: { prompt: string, systemInstruction?: string }) => apiClient.post('/ai/generate', data).then(res => res.data),
    analyzeGithub: (repoUrl: string) => apiClient.post('/ai/analyze-github', { repoUrl }).then(res => res.data),
    generate: async (payload: { prompt: string; provider?: string; task?: string; context?: string }): Promise<any> => {
      const response = await apiClient.post<any>('/ai/generate', payload);
      return response.data;
    },
    fetchModels: async (payload: { apiKey: string; endpoint?: string }): Promise<any> => {
        const response = await apiClient.post<any>('/ai/models', payload);
        return response.data;
    }
  }
};

export default api;
