import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Sparkles, RefreshCw } from 'lucide-react';
import { Button } from './button';

interface AISummaryModalProps {
  isOpen: boolean;
  onClose: () => void;
  project: any;
  startIndex?: number;
}

export const AISummaryModal = ({ isOpen, onClose, project, startIndex = 0 }: AISummaryModalProps) => {
  const [displayedText, setDisplayedText] = useState('');
  const [isTyping, setIsTyping] = useState(false);

  // Fallback if no summaries
  const defaultSummary = `Project: ${project?.title}\n\n${project?.description || 'No description available.'}`;
  const summaries = project?.summaries && project.summaries.length > 0 
    ? project.summaries 
    : [{ content: defaultSummary, version: 1 }];

  // Ensure index is valid
  const safeIndex = startIndex % summaries.length;
  const currentSummary = summaries[safeIndex]?.content || "";

  useEffect(() => {
    if (isOpen) {
      setDisplayedText('');
      setIsTyping(true);
      let i = 0;
      // Faster typing for longer text
      const speed = currentSummary.length > 200 ? 15 : 30;
      
      const timer = setInterval(() => {
        if (i < currentSummary.length) {
          setDisplayedText(currentSummary.substring(0, i + 1));
          i++;
        } else {
          setIsTyping(false);
          clearInterval(timer);
        }
      }, speed);
      return () => clearInterval(timer);
    }
  }, [isOpen, safeIndex, currentSummary]);

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="absolute inset-0 bg-black/60 backdrop-blur-sm"
          />
          
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9, y: 20 }}
            className="relative bg-card border border-primary/20 rounded-xl shadow-2xl w-full max-w-lg overflow-hidden z-10"
          >
            {/* Header */}
            <div className="flex items-center justify-between p-4 border-b border-border/50 bg-muted/30">
              <div className="flex items-center gap-2 text-primary">
                <div className="p-1.5 rounded-md bg-primary/10">
                  <Sparkles className="w-4 h-4" />
                </div>
                <span className="font-semibold text-sm">AI Project Insight</span>
              </div>
              <button 
                onClick={onClose} 
                className="p-1 rounded-md hover:bg-muted text-muted-foreground hover:text-foreground transition-colors"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Content */}
            <div className="p-6 min-h-[150px] bg-card/50">
               <div className="font-mono text-sm leading-relaxed text-foreground/90 whitespace-pre-wrap">
                 {displayedText}
                 {isTyping && <span className="inline-block w-2 h-4 ml-1 bg-primary animate-pulse align-middle" />}
               </div>
            </div>

            {/* Footer */}
            <div className="p-3 border-t border-border/50 bg-muted/30 flex justify-between items-center">
              <span className="text-xs text-muted-foreground font-mono flex items-center gap-1.5">
                <Sparkles className="w-3 h-3" />
                Generated by Gemini 2.5 Flash
              </span>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
};
